var searchData=
[
  ['partial_20document_20persistency_568',['Partial Document Persistency',['../group___partial___document___persistency.html',1,'']]],
  ['persistentid_569',['persistentID',['../group___model___audio___source.html#a3f0900cc3b1f1842d5a46a55a9118115',1,'ARAAudioSourceProperties::persistentID()'],['../group___model___audio___modification.html#ab8555a3a444529f8aceb783e5604eb63',1,'ARAAudioModificationProperties::persistentID()'],['../group___processing___algorithm___selection.html#ac2161cb709040ff15303176c74692374',1,'ARAProcessingAlgorithmProperties::persistentID()']]],
  ['pitchinterpreter_570',['PitchInterpreter',['../group___a_r_a___library___utility___pitch___interpretation.html#class_a_r_a_1_1_pitch_interpreter',1,'ARA::PitchInterpreter'],['../group___a_r_a___library___utility___pitch___interpretation.html#ad7cd26957813690d55ea9c439d65edd2',1,'ARA::PitchInterpreter::PitchInterpreter()'],['../group___a_r_a___library___utility___pitch___interpretation.html#ad7cd26957813690d55ea9c439d65edd2',1,'ARA::ChordInterpreter::PitchInterpreter()'],['../group___a_r_a___library___utility___pitch___interpretation.html#ad7cd26957813690d55ea9c439d65edd2',1,'ARA::KeySignatureInterpreter::PitchInterpreter()']]],
  ['pitchnumber_571',['pitchNumber',['../group___model___notes.html#a348c579958fe8796f06c80c4bd8818d7',1,'ARAContentNote']]],
  ['playback_20controller_20interface_572',['Playback Controller Interface',['../group___host___playback___controller___interface.html',1,'']]],
  ['playback_20region_573',['Playback Region',['../group___model___playback___region.html',1,'']]],
  ['playback_20renderer_20interface_20_28added_20in_20ara_202_2e0_29_574',['Playback Renderer Interface (Added In ARA 2.0)',['../group___playback___renderer___interface.html',1,'']]],
  ['playbackcontrollerinterface_575',['PlaybackControllerInterface',['../group___a_r_a___library___host___dispatch___host___interfaces.html#class_a_r_a_1_1_host_1_1_playback_controller_interface',1,'ARA::Host']]],
  ['playbackregion_576',['PlaybackRegion',['../group___a_r_a___library___a_r_a_plug___model___objects.html#class_a_r_a_1_1_plug_in_1_1_playback_region',1,'ARA::PlugIn::PlaybackRegion'],['../group___a_r_a___library___a_r_a_plug___model___objects.html#ac5e8da415652b2a8e20ef703e564bcfc',1,'ARA::PlugIn::PlaybackRegion::PlaybackRegion()']]],
  ['playbackregionrefs_577',['playbackRegionRefs',['../group___editor___view___interface.html#a86ca6132af9d8ae816d9acf1a4afc243',1,'ARAViewSelection']]],
  ['playbackregionrefscount_578',['playbackRegionRefsCount',['../group___editor___view___interface.html#a825a34faf5c450e5083f626a692fd682',1,'ARAViewSelection']]],
  ['playbackrenderer_579',['PlaybackRenderer',['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#class_a_r_a_1_1_host_1_1_playback_renderer',1,'ARA::Host::PlaybackRenderer'],['../group___a_r_a___library___a_r_a_plug___plug_in_instance_roles.html#class_a_r_a_1_1_plug_in_1_1_playback_renderer',1,'ARA::PlugIn::PlaybackRenderer']]],
  ['playbackrendererinterface_580',['PlaybackRendererInterface',['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#class_a_r_a_1_1_plug_in_1_1_playback_renderer_interface',1,'ARA::PlugIn']]],
  ['plug_2din_20dispatch_581',['Plug-In Dispatch',['../group___a_r_a___library___plug_in___dispatch.html',1,'']]],
  ['plug_2din_20entry_582',['Plug-In Entry',['../group___a_r_a___library___a_r_a_plug___plug_in_entry.html',1,'']]],
  ['plug_2din_20extension_583',['Plug-In Extension',['../group___plug-_in___extension.html',1,'']]],
  ['plug_2din_20factory_584',['Plug-In Factory',['../group___plug-_in___factory.html',1,'']]],
  ['plug_2din_20instance_20roles_585',['Plug-In Instance Roles',['../group___a_r_a___library___a_r_a_plug___plug_in_instance_roles.html',1,'']]],
  ['plug_2din_20interface_20wrappers_586',['Plug-In Interface Wrappers',['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html',1,'']]],
  ['plug_2din_20interfaces_587',['Plug-In Interfaces',['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html',1,'(Global Namespace)'],['../group___plug___in___interfaces.html',1,'(Global Namespace)']]],
  ['pluginentry_588',['PlugInEntry',['../group___a_r_a___library___a_r_a_plug___plug_in_entry.html#class_a_r_a_1_1_plug_in_1_1_plug_in_entry',1,'ARA::PlugIn']]],
  ['pluginextension_589',['PlugInExtension',['../group___a_r_a___library___a_r_a_plug___plug_in_instance_roles.html#class_a_r_a_1_1_plug_in_1_1_plug_in_extension',1,'ARA::PlugIn']]],
  ['pluginextensioninstance_590',['PlugInExtensionInstance',['../group___a_r_a___library___host___dispatch.html#class_a_r_a_1_1_host_1_1_plug_in_extension_instance',1,'ARA::Host::PlugInExtensionInstance'],['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#class_a_r_a_1_1_plug_in_1_1_plug_in_extension_instance',1,'ARA::PlugIn::PlugInExtensionInstance']]],
  ['pluginname_591',['plugInName',['../group___plug-_in___factory.html#a341b269750f1c71e37d9717a6c04cd46',1,'ARAFactory']]],
  ['position_592',['position',['../group___model___timeline.html#a0de8d399889f2bea827217bb918d8ea4',1,'ARAContentBarSignature::position()'],['../group___model___tuning___key___signatures__and___chords.html#a154f4187c8d6e5d6fa2ebc1f25f9d58e',1,'ARAContentKeySignature::position()'],['../group___model___tuning___key___signatures__and___chords.html#a857cfb0099ae353bb9214f4f81ae8bcf',1,'ARAContentChord::position()']]],
  ['processing_20algorithm_20selection_593',['Processing Algorithm Selection',['../group___processing___algorithm___selection.html',1,'']]],
  ['properties_594',['Properties',['../group___a_r_a___library___host___dispatch.html#ga1973ea14b641179d69ebb097db9391dd',1,'ARA::Host']]],
  ['propertiesptr_595',['PropertiesPtr',['../group___a_r_a___library___plug_in___dispatch.html#ga2e2a73fb8a1840a2b6ea92e667134825',1,'ARA::PlugIn']]]
];
