var searchData=
[
  ['editor_20renderer_20interface_20_28added_20in_20ara_202_2e0_29_290',['Editor Renderer Interface (Added In ARA 2.0)',['../group___editor___renderer___interface.html',1,'']]],
  ['editor_20view_20interface_20_28added_20in_20ara_202_2e0_29_291',['Editor View Interface (Added In ARA 2.0)',['../group___editor___view___interface.html',1,'']]],
  ['editorrenderer_292',['EditorRenderer',['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#class_a_r_a_1_1_host_1_1_editor_renderer',1,'ARA::Host::EditorRenderer'],['../group___a_r_a___library___a_r_a_plug___plug_in_instance_roles.html#class_a_r_a_1_1_plug_in_1_1_editor_renderer',1,'ARA::PlugIn::EditorRenderer']]],
  ['editorrendererinterface_293',['EditorRendererInterface',['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#class_a_r_a_1_1_plug_in_1_1_editor_renderer_interface',1,'ARA::PlugIn']]],
  ['editorview_294',['EditorView',['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#class_a_r_a_1_1_host_1_1_editor_view',1,'ARA::Host::EditorView'],['../group___a_r_a___library___a_r_a_plug___plug_in_instance_roles.html#class_a_r_a_1_1_plug_in_1_1_editor_view',1,'ARA::PlugIn::EditorView']]],
  ['editorviewinterface_295',['EditorViewInterface',['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#class_a_r_a_1_1_plug_in_1_1_editor_view_interface',1,'ARA::PlugIn']]],
  ['enableaudiosourcesamplesaccess_296',['enableAudioSourceSamplesAccess',['../group___plug-_in___document___controller.html#a25219110cde06efeceeda830a23be94a',1,'ARADocumentControllerInterface::enableAudioSourceSamplesAccess()'],['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#a03c19ecade2cc7e2a988166d2aaaebd1',1,'ARA::Host::DocumentController::enableAudioSourceSamplesAccess()'],['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#ab05b440d0590981cf47c37171b0e0af7',1,'ARA::PlugIn::DocumentControllerInterface::enableAudioSourceSamplesAccess()']]],
  ['endediting_297',['endEditing',['../group___plug-_in___document___controller.html#ab4946909515472d8ea4f5f1ee5cac599',1,'ARADocumentControllerInterface::endEditing()'],['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#a55e6e57a97e7b22de22736e94dcb86f2',1,'ARA::Host::DocumentController::endEditing()'],['../group___a_r_a___library___host___dispatch___plug-_in___interfaces.html#a40d465eb57035ff705d9576aa7bb63a6',1,'ARA::PlugIn::DocumentControllerInterface::endEditing()']]],
  ['endrestoringdocumentfromarchive_298',['endRestoringDocumentFromArchive',['../group___plug-_in___document___controller.html#a363873f0f7d49e2f94b814d93bd30a0d',1,'ARADocumentControllerInterface::endRestoringDocumentFromArchive()'],['../group___a_r_a___library___host___dispatch___plug-_in___interface___wrappers.html#a708cc77b4aa3e2be0f345ac44f12c415',1,'ARA::Host::DocumentController::endRestoringDocumentFromArchive()']]],
  ['enums_299',['Enums',['../group___enums.html',1,'']]],
  ['everythingisaffected_300',['everythingIsAffected',['../group___a_r_a___library___utility___content___update___scopes.html#a19a5c748bbf83e35a6886d43b8f56f0e',1,'ARA::ContentUpdateScopes']]]
];
