var searchData=
[
  ['harmoniesareaffected_393',['harmoniesAreAffected',['../group___a_r_a___library___utility___content___update___scopes.html#a5ca3529c1d8cc06b841dbf643d5695f9',1,'ARA::ContentUpdateScopes']]],
  ['hascontentbasedfadeathead_394',['hasContentBasedFadeAtHead',['../group___a_r_a___library___a_r_a_plug___model___objects.html#a59b325ca6d75acda02d6fa82f571ce24',1,'ARA::PlugIn::PlaybackRegion']]],
  ['hascontentbasedfadeattail_395',['hasContentBasedFadeAtTail',['../group___a_r_a___library___a_r_a_plug___model___objects.html#ac22849ead8d9bd08d9e2fb3b10cd0a77',1,'ARA::PlugIn::PlaybackRegion']]],
  ['hasmajorseventh_396',['hasMajorSeventh',['../group___a_r_a___library___utility___pitch___interpretation.html#aa79e0d682aea96871c2344ad3dface09',1,'ARA::KeySignatureInterpreter']]],
  ['hasmajorthird_397',['hasMajorThird',['../group___a_r_a___library___utility___pitch___interpretation.html#a3712c2b61faa7ee053b605ad7193c4cf',1,'ARA::KeySignatureInterpreter']]],
  ['hasminorseventh_398',['hasMinorSeventh',['../group___a_r_a___library___utility___pitch___interpretation.html#a7c2aa5094b179800b2ce896b4619476d',1,'ARA::KeySignatureInterpreter']]],
  ['hasminorthird_399',['hasMinorThird',['../group___a_r_a___library___utility___pitch___interpretation.html#a95782b708c157d026c2892a0f97e8e68',1,'ARA::KeySignatureInterpreter']]],
  ['highestsupportedapigeneration_400',['highestSupportedApiGeneration',['../group___plug-_in___factory.html#a03d647ac80a6d6bcea83c6367d23c837',1,'ARAFactory']]],
  ['host_20dispatch_401',['Host Dispatch',['../group___a_r_a___library___host___dispatch.html',1,'']]],
  ['host_20interface_20wrappers_402',['Host Interface Wrappers',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html',1,'']]],
  ['host_20interfaces_403',['Host Interfaces',['../group___a_r_a___library___host___dispatch___host___interfaces.html',1,'(Global Namespace)'],['../group___host___interfaces.html',1,'(Global Namespace)']]],
  ['hostarchivereader_404',['HostArchiveReader',['../group___a_r_a___library___a_r_a_plug___utility___classes.html#class_a_r_a_1_1_plug_in_1_1_host_archive_reader',1,'ARA::PlugIn']]],
  ['hostarchivewriter_405',['HostArchiveWriter',['../group___a_r_a___library___a_r_a_plug___utility___classes.html#class_a_r_a_1_1_plug_in_1_1_host_archive_writer',1,'ARA::PlugIn']]],
  ['hostarchivingcontroller_406',['HostArchivingController',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html#class_a_r_a_1_1_plug_in_1_1_host_archiving_controller',1,'ARA::PlugIn']]],
  ['hostaudioaccesscontroller_407',['HostAudioAccessController',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html#class_a_r_a_1_1_plug_in_1_1_host_audio_access_controller',1,'ARA::PlugIn']]],
  ['hostaudioreader_408',['HostAudioReader',['../group___a_r_a___library___a_r_a_plug___utility___classes.html#class_a_r_a_1_1_plug_in_1_1_host_audio_reader',1,'ARA::PlugIn::HostAudioReader'],['../group___a_r_a___library___a_r_a_plug___utility___classes.html#a51e06468c0e367e1b9223755dcacd33f',1,'ARA::PlugIn::HostAudioReader::HostAudioReader(const AudioSource *audioSource, bool use64BitSamples=false) noexcept'],['../group___a_r_a___library___a_r_a_plug___utility___classes.html#a0737fca82de66047ad66c905c088475e',1,'ARA::PlugIn::HostAudioReader::HostAudioReader(HostAudioAccessController *audioAccessController, ARAAudioSourceHostRef audioSourceHostRef, bool use64BitSamples=false) noexcept']]],
  ['hostcontentaccesscontroller_409',['HostContentAccessController',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html#class_a_r_a_1_1_plug_in_1_1_host_content_access_controller',1,'ARA::PlugIn']]],
  ['hostcontentreader_410',['HostContentReader',['../group___a_r_a___library___a_r_a_plug___utility___classes.html#class_a_r_a_1_1_plug_in_1_1_host_content_reader',1,'ARA::PlugIn::HostContentReader&lt; contentType &gt;'],['../group___a_r_a___library___a_r_a_plug___utility___classes.html#a5ba730ddd8b56a891a80124d94f7d334',1,'ARA::PlugIn::HostContentReader::HostContentReader(const MusicalContext *musicalContext, const ARAContentTimeRange *range=nullptr) noexcept'],['../group___a_r_a___library___a_r_a_plug___utility___classes.html#a36fff11a38a8e0123681fd04404e0a34',1,'ARA::PlugIn::HostContentReader::HostContentReader(const AudioSource *audioSource, const ARAContentTimeRange *range=nullptr) noexcept']]],
  ['hostcontentreaderbase_411',['HostContentReaderBase',['../group___a_r_a___library___a_r_a_plug___utility___classes.html#gaff578b1952af3075bbe57dcff306364c',1,'ARA::PlugIn']]],
  ['hostmodelupdatecontroller_412',['HostModelUpdateController',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html#class_a_r_a_1_1_plug_in_1_1_host_model_update_controller',1,'ARA::PlugIn']]],
  ['hostplaybackcontroller_413',['HostPlaybackController',['../group___a_r_a___library___host___dispatch___host___interface___wrappers.html#class_a_r_a_1_1_plug_in_1_1_host_playback_controller',1,'ARA::PlugIn']]]
];
